spring:
  application:
    name: hackathon2025-backend
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID}
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash-001
              max-tokens: 1000
              temperature: 0.7


