spring:
  application:
    name: hackathon2025-backend
  data:
    redis:
      url: redis://localhost:6379
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID}
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro
              max-tokens: 5000
              temperature: 0.7

        embedding:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID}
          location: us-central1
          options:
            model: text-embedding-004
