export const allLangCodes = [
  "af-ZA",
  "am-ET",
  "ar-XA",
  "bg-BG",
  "bn-IN",
  "ca-ES",
  "cmn-CN",
  "cmn-TW",
  "cs-CZ",
  "da-DK",
  "de-DE",
  "el-GR",
  "en-AU",
  "en-GB",
  "en-IN",
  "en-US",
  "es-ES",
  "es-US",
  "et-EE",
  "eu-ES",
  "fi-FI",
  "fil-PH",
  "fr-CA",
  "fr-FR",
  "gl-ES",
  "gu-IN",
  "he-IL",
  "hi-IN",
  "hu-HU",
  "id-ID",
  "is-IS",
  "it-IT",
  "ja-JP",
  "kn-IN",
  "ko-KR",
  "lt-LT",
  "lv-LV",
  "ml-IN",
  "mr-IN",
  "ms-MY",
  "nb-NO",
  "nl-BE",
  "nl-NL",
  "pa-IN",
  "pl-PL",
  "pt-BR",
  "pt-PT",
  "ro-RO",
  "ru-RU",
  "sk-SK",
  "sr-RS",
  "sv-SE",
  "sw-KE",
  "ta-IN",
  "te-IN",
  "th-TH",
  "tr-TR",
  "uk-UA",
  "ur-IN",
  "vi-VN",
  "yue-HK",
]

export const languageCodeMap: Record<string, string> = {
  "af-ZA": "Afrikaans (South Africa)",
  "am-ET": "Amharic (Ethiopia)",
  "ar-XA": "Arabic",
  "bg-BG": "Bulgarian (Bulgaria)",
  "bn-IN": "Bengali (India)",
  "ca-ES": "Catalan (Spain)",
  "cmn-CN": "Mandarin Chinese (China)",
  "cmn-TW": "Mandarin Chinese (Taiwan)",
  "cs-CZ": "Czech (Czech Republic)",
  "da-DK": "Danish (Denmark)",
  "de-DE": "German (Germany)",
  "el-GR": "Greek (Greece)",
  "en-AU": "English (Australia)",
  "en-GB": "English (United Kingdom)",
  "en-IN": "English (India)",
  "en-US": "English (United States)",
  "es-ES": "Spanish (Spain)",
  "es-US": "Spanish (United States)",
  "et-EE": "Estonian (Estonia)",
  "eu-ES": "Basque (Spain)",
  "fi-FI": "Finnish (Finland)",
  "fil-PH": "Filipino (Philippines)",
  "fr-CA": "French (Canada)",
  "fr-FR": "French (France)",
  "gl-ES": "Galician (Spain)",
  "gu-IN": "Gujarati (India)",
  "he-IL": "Hebrew (Israel)",
  "hi-IN": "Hindi (India)",
  "hu-HU": "Hungarian (Hungary)",
  "id-ID": "Indonesian (Indonesia)",
  "is-IS": "Icelandic (Iceland)",
  "it-IT": "Italian (Italy)",
  "ja-JP": "Japanese (Japan)",
  "kn-IN": "Kannada (India)",
  "ko-KR": "Korean (South Korea)",
  "lt-LT": "Lithuanian (Lithuania)",
  "lv-LV": "Latvian (Latvia)",
  "ml-IN": "Malayalam (India)",
  "mr-IN": "Marathi (India)",
  "ms-MY": "Malay (Malaysia)",
  "nb-NO": "Norwegian Bokmål (Norway)",
  "nl-BE": "Dutch (Belgium)",
  "nl-NL": "Dutch (Netherlands)",
  "pa-IN": "Punjabi (India)",
  "pl-PL": "Polish (Poland)",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  "ro-RO": "Romanian (Romania)",
  "ru-RU": "Russian (Russia)",
  "sk-SK": "Slovak (Slovakia)",
  "sr-RS": "Serbian (Serbia)",
  "sv-SE": "Swedish (Sweden)",
  "sw-KE": "Swahili (Kenya)",
  "ta-IN": "Tamil (India)",
  "te-IN": "Telugu (India)",
  "th-TH": "Thai (Thailand)",
  "tr-TR": "Turkish (Türkiye)",
  "uk-UA": "Ukrainian (Ukraine)",
  "ur-IN": "Urdu (India)",
  "vi-VN": "Vietnamese (Vietnam)",
  "yue-HK": "Cantonese (Hong Kong)",
}
